### PR TITLE
Goci 2578 tw add association level ef os

### PR DESCRIPTION
**Pull request by twhetzel**
This update is currently being tested by the curators. If no issues are reported by end of day Monday (Feb. 18) it can be merged into master.

### CODE REVIEW

**Comment by DSuveges** [comment]
All the modifications make sense. Just a question: do we need a catch on the UI side to handle the default 'none' values?

**Comment by twhetzel** [comment]
Which 'none' values?

**Comment by DSuveges** [comment]
> Which 'none' values?
I should have inserted the comment to the code. I still learning how to user github. So in `OLSData.py` the default return object looks like this: 

```python
no_results = {'iri': None, 'synonyms': None, 'short_form': None, 'label': None, 'description': None}
```
Do the UI code need to be changed to handle this kind of object?

**Comment by twhetzel** [comment]
I don't think a UI update is needed. This default return object has been in the code since the code was first developed. The change here is using it with the other new methods in the module. However, to be safe we can check this in the site.

**Pull request merged**
